### ISSUE TITLE
Consider adopting contributing guidelines?

### ISSUE THREAD

**Issue by bcomnes** [aredridel/homebrew-iojs#11]
I'm loving all the drive by contributions!  What do you (all) think about adopting something like: https://github.com/bcomnes/gh-release/blob/master/CONTRIBUTING.md for this repo?

**Comment by aredridel** [comment]
:+1: 

Releases aren't relevant, since if it goes to master it's live, but works for me!

**Comment by bcomnes** [comment]
Yeah, im cool with relaxing any release policy.

**Comment by hmalphettes** [comment]
Cheers @bcomnes and @aredridel !
Just a question:
I had understood this was a stop gap measure until all the goodness and experience accumulated here trickles down to homebrew's master branch: are we in fact expecting this project to be long lived?

**Comment by bcomnes** [comment]
I'm not sure.  It depends on how the official homebrew formula eventually turns out.  There is discussion about maintaining iojs run repos https://github.com/iojs/io.js/issues/640 but I think its more targeted at harder to update repos like apt or yum.  I would like to use the official formula eventually but for now this meets my needs.

**Comment by aredridel** [comment]
Yeah, we'll see how it plays out. I'm happy having this be an alternative to a complicated set of homebrew integrations for iojs/node/npm.

**Comment by bcomnes** [comment]
I'll add in the document with some minor changes soonish.
