### ISSUE TITLE
Add travis OS X tests

### ISSUE THREAD

**Issue by bcomnes** [aredridel/homebrew-iojs#20]
http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/ 

Looks like it wouldn't be hard to add CI testing to this

**Comment by aredridel** [comment]
Ooh, yeah!

**Comment by rstacruz** [comment]
I wonder what hell would be raised if Homebrew enabled CI testing all the formulae :)

**Comment by rstacruz** [comment]
curious: how would the testing strategy be? make a test script that will install homebrew, then `brew install ./iojs.rb`? Is there a way to do an "unattended" installation of homebrew?

**Comment by bcomnes** [comment]
@rstacruz It probably would cause some problems... Luckily homebrew has their own, crowdfunded CI system in place: https://www.kickstarter.com/projects/homebrew/brew-test-bot

This doesn't cover taps though.  Pretty much we would do something like
- brew update
- brew install aredridel/iojs/iojs --build-from-source
- brew test aredridel/iojs/iojs (this would test native add ons or...)
- npm install buffertools (to check if the patch worked)

This would tell us that everything builds okay, and we can test for successful installs

**Comment by bcomnes** [comment]
Going to poke at this again.

**Comment by bcomnes** [comment]
Didn't get to it and am going to be out of town.  Closing until I have time to fix this.  Anyone feel free to re-open if they want to hop on this.  I will revisit time permitting.
