### ISSUE TITLE
Include node 4.0?

### ISSUE THREAD

**Issue by bcomnes** [aredridel/homebrew-iojs#26]
Since we can't have good things quite yet, what do yall think about including an alternate node 4.0 recipe for the time being?  (since 4.0 has yet to land in the main repo?)

**Comment by aredridel** [comment]
Heck yes. An alias to iojs, maybe? Or any of the other solutions.

**Comment by bcomnes** [comment]
Was thinking it could just be a duplicate of node, requiring a fully qualified formula name to interact with, but for the sake of practicality, and longevity, maybe giving it some kind of alternate name would be better due to the weirdness formula name duplication can cause.

**Comment by aredridel** [comment]
Yeah. I dunno. We're already doing that with iojs, and I think more encouragement for those issues to get straightened out is good.

**Comment by bcomnes** [comment]
maybe node-alt or node-unofficial would be good, non-conflicting names.  Ill try to poke around tonight when I'm back on a mac.

**Comment by hmalphettes** [comment]
So far I took our repository and turned it into a nodejs-v4 formula:
https://github.com/hmalphettes/homebrew-node

Once we settle for a name let me know if you want me to push it here or open a PR.

**Comment by bcomnes** [comment]
@hmalphettes I jumped when I should have looked and landed a https://github.com/aredridel/homebrew-iojs/pull/27 😁 sorry about that.

**Comment by hmalphettes** [comment]
@bcomnes cheers for that one.
